<?php

/**
 * Created by PhpStorm.
 * User: Alex
 * Date: 2015-11-26
 * Time: 11:17 AM
 */
class _Recovery extends Model
{
    /**
     * _Recovery constructor.
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Returns the ID of the user who's email is $email
     * @param $email string email to be used to find the ID
     * @return bool|int False if no ID belongs to the email, returns the ID otherwise
     */
    public function getUIDFromEmail($email)
    {
        $res = $this->db->select("SELECT `user_id` FROM `users` WHERE email = :email ", array(':email' => $email));

        if (count($res) == 1)
            return $res[0]['user_id'];
        else
            return false;
    }

    /**
     * Gets the first and last name of the given userID
     * @param $uid int id of the user
     * @return array Array indexed by first_name and last_name
     */
    private function getName($uid)
    {
        return $this->db->select("SELECT first_name, last_name FROM users WHERE user_id = :id", array(':id' => $uid))[0];
    }

    /**
     * Returns the ID belonging to the user who created the given reset key
     * @param $key string MD5 reset key generated in the newRequest() method
     * @return bool|int False if no key exists, The ID of the user otherwise.
     */
    private function getUIDFromKey($key)
    {
        $res = $this->db->select("SELECT `user_id` FROM `password_recovery` WHERE `reset_key` = :key ", array(':key' => $key));

        if (count($res) == 1)
            return $res[0]['user_id'];
        else
            return false;
    }

    /**
     * Creates a new request using the given email
     * @param $email string Email to be used to create a new reset request
     * @return int Returns 0 if no ID matching the email exists, 1 if a recovery is sent successfully, -1 otherwise
     */
    public function newRequest($email)
    {
        $key = md5(microtime() . rand()); //generate a random and unique key to identify the reset request

        $uid = $this->getUIDFromEmail($email);

        if ($uid === false) {
            //Email doesn't exist error;
            return 0;
        }

        if (!$this->db->insert('password_recovery', array('reset_key' => $key, 'user_id' => $uid))) {
            //Generic error
            return -1;
        }

        $name = $this->getName($uid);

        if ($this->sendRecovery($email, $key, $name['first_name'], $name['last_name']))
            return 1;
        else
            return -1;
    }

    /**
     * Sends the email to the given email
     * @param $email string Email being mailed to
     * @param $key string Unique reset key generated by the newRequest
     * @param $fname string First name of user being emailed (For anti-Spam)
     * @param $lname string Last name of the user being emailed (For anti-spam)
     * @return bool True if successfully sent, False otherwise
     * @throws Exception
     * @throws phpmailerException
     */
    public function sendRecovery($email, $key, $fname, $lname)
    {
        $mail = new PHPMailer();

        $mail->isSMTP();
        //$mail->SMTPDebug =3;
        $mail->Host = EMAIL_HOST;
        $mail->SMTPAuth = true;
        $mail->Username = EMAIL_USER;
        $mail->Password = EMAIL_PASS;
        $mail->Port = 25;

        $mail->setFrom(EMAIL_USER, 'BanaBook Account Recovery');
        $mail->addAddress($email, $fname . ' ' . $lname);

        $mail->isHTML(true);

        $mail->Subject = 'Dammit, you forgot your password again?';
        $mail->Body = $this->makeMessage($key, $email, $fname . ' ' . $lname);

        if (!$mail->send()) {
            echo 'Message could not be sent.';
            echo 'Mailer Error: ' . $mail->ErrorInfo;
            return false;
        } else {
            return true;
        }

    }

    /**
     * Generate the message contents for the email
     * @param $key string the Password reset key
     * @param $email string the email being sent to
     * @param $name string Name of the user being sent to
     * @return string The generated message
     */
    private function makeMessage($key, $email, $name)
    {
        $url = URL . 'auth/doReset?email=' . $email . '&key=' . $key;

        //Get the contents of the template
        $htmlFile = file_get_contents(PATH . 'views/mail/recovery.php');

        //replace placeolders in the message with variables
        $htmlFile = str_replace("{URL}", $url, $htmlFile);
        $htmlFile = str_replace("{NAME}", $name, $htmlFile);

        return $htmlFile;
    }

    /**
     * Validates that there is a pending request for a password reset matching the UID and the key
     * @param $uid int the ID of the user being checked against the Key
     * @param $key string the reset key to be checked against the userID
     * @return bool|int False if not valid request, UserID if its valid
     */
    public function validateRequest($uid, $key)
    {
        if ($uid != $this->getUIDFromKey($key)) {
            return false;
        } else
            return $uid;

    }

    /**
     * Resets the password returns true if successful, false otherwise
     * @param $uid int UserID of the user having a password reset
     * @param $key string Unique reset key used to validate the reset request
     * @param $password string new password
     * @return bool True if successful, False otherwise
     */
    public function resetPassword($uid, $key, $password)
    {
        $password = Hash::create('sha256', $password, HASH_PW_KEY);
        if ($this->validateRequest($uid, $key) === false)
            return false;
        elseif ($this->db->update('users', array('password' => $password), "`user_id` = $uid")) {
            $this->db->delete('password_recovery', "`user_id` = $uid");
            return true;
        } else {
            return false;
        }
    }

}